name: fluttercommerce
description: Shopping UI design in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  country_pickers: ^2.0.0
  flutter_icons: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^4.0.0
  #division: ^0.9.0
  division:
  page_transition: ^2.0.5
  bottom_navy_bar: ^6.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_xlider: ^3.4.0
  intro_views_flutter: ^3.2.0
  rflutter_alert: ^2.0.4
  hidden_drawer_menu: ^3.0.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf
